/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'grimrose' at '16/06/12 16:08' with Gradle 2.13
 *
 * @author grimrose, @date 16/06/12 16:08
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
