/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'grimrose' at '16/06/12 16:08' with Gradle 2.13
 *
 * @author grimrose, @date 16/06/12 16:08
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
